name: BUILD

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 */8 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [mutter-performance]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Build package"
      run: ./build-aur-action/run-arm64.sh ${{ matrix.repos }}

    - uses: actions/upload-artifact@v3
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}
